// flow-typed signature: 025225a8d6ba4f972ec8704174def0d8
// flow-typed version: <<STUB>>/webpack-udev-server_v0.8.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-udev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-udev-server' {
  declare export class Client {
    getStats(name: string): Promise<*>;
  }
  declare export function createClient(): Client;
}
